linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gosec
    - gochecknoglobals
    - lll
    - golint
    - dupl
    - goimports

service:
  golangci-lint-version: 1.13.x # use fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed"