sudo: false
language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -coverprofile=coverage.txt -covermode=atomic ./...

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
